name: Build binaries

on:
  schedule:
    - cron: "0 5 */1 * *"
  push:
  pull_request:
    paths:
    - '.github/workflows/*.yml'
    - './scripts/*.sh'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Checkout builder
        uses: actions/checkout@v1

      - name: Install arm toolchain
        run: ./scripts/install_arm.sh

      - name: Install ESP-IDF toolchain
        run: ./scripts/install_espidf.sh

      - name: Checkout ulab/micropython
        run: ./scripts/init.sh

      - name: Create artifacts directory
        run: mkdir ./artifacts

      # this section is only for test purposes
      # - name: Compile unix port
      #   if: always()
      # #   run: ./scripts/unix.sh

      - name: Compile for ESP32 GENERIC 
        if: always()
        run: ./scripts/esp32/generic.sh

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: "latest"
          title: "Release date ${{ steps.date.outputs.date }}"
          files: ./artifacts/*
