name: Build binaries

on:
  schedule:
    - cron: "0 5 */1 * *"
  push:
  pull_request:
    paths:
    - '.github/workflows/*.yml'
    - './scripts/*.sh'

jobs:
  build:
    runs-on: self-hosted
    steps:

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: mount ramfs of build
        run: sudo /usr/local/bin/mount_ramfs.sh

      - name: Checkout builder
        uses: actions/checkout@v1

      - name: Install arm toolchain
        run: ./scripts/install_arm.sh

      - name: Install ESP-IDF toolchain
        run: ./scripts/install_espidf.sh

      - name: Checkout ulab/micropython
        run: ./scripts/init.sh

      - name: Create artifacts directory
        run: mkdir ./artifacts

      - name: Compile for ESP32-S3 8MB SPIRAM/16MB Flash
        if: always()
        run: ./scripts/esp32/generic-s3-spiram-16mb-ota.sh

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: "latest"
          title: "Release date ${{ steps.date.outputs.date }}"
          files: ./artifacts/*
